# Generated by Django 5.1.6 on 2025-05-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('public_event', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Tournament', 'Tournament'), ('Bake Sale', 'Bake Sale'), ('School Event', 'School Event')], default='Bake Sale')),
                ('type2', models.CharField(choices=[('Round Robin', 'Round Robin'), ('Single Elimination', 'Single Elimination'), ('Double Elimination', 'Double Elimination')], default=None, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
