# Generated by Django 5.1.6 on 2025-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type2',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateField(default=None),
        ),
    ]
