# Generated by Django 5.1.1 on 2025-06-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Announcements', '0002_announcements_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='user',
        ),
    ]
