# Generated by Django 5.1.6 on 2025-05-01 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('room_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('email', models.EmailField(max_length=250, verbose_name='')),
                ('teacher', models.CharField(default='null', max_length=100)),
                ('meeting_day', models.TextField(blank=True)),
                ('club_members', models.ManyToManyField(blank=True, related_name='clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
