# Generated by Django 5.1.6 on 2025-06-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
